### ISSUE TITLE
hln.be

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistdutch#19]
Two placeholders on the frontpage (and one in the feed below articles on article pages) when the window is between 810~890px wide. I propose `hln.be#?#.tile-grid > li[class*=" tile-large-"]:-abp-has(> .ankeiler--advertisement)`
![image](https://user-images.githubusercontent.com/22780683/132014753-74b78a90-8a64-40e5-977d-1cec339ab3e1.png)

Adblockers: uBO 1.37.3b20 + IDCAC 3.3.2
Browser: Chrome 93.0.4577.63 x64
OS: Windows 10 21H1 x64
Lists in use: ↓
![image](https://user-images.githubusercontent.com/22780683/132014947-4f8502a3-cfe7-42ce-9e16-e6259ba75ae3.png)

**Comment by Khrin** [comment]
0 filters out of 615?  Huh, really?

Anyway, I don't think that's necessary to block it, at the moment.

**Comment by DandelionSprout** [comment]
Just to be 100% on the sure side, I have both EasyList Dutch and AdGuard Dutch Filter turned on, and the latter list embeds the former one.
