### ISSUE TITLE
dagbladdewest.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistdutch#24]
That site is ***weird***. Clicking anywhere on the frontpage, causes a redirect to `https://viapizza.online/?ts_id=117`, which looks identical to `dagbladdewest.com`. Moreover, it uses some kind of script to prevent the site from being interacted with while the devlogger is open.

For the plentiful of ads in the rightside bar, I propose:
```
dagbladdewest.com###right-sidebar .elementor-widget-wrap
dagbladdewest.com##.swiper-wrapper
||dagbladdewest.com/*_728x90px_*.jpg|
```

For the redirects, I wasn't able to get `##iframe[src*=viapizza]` nor `##form[action*="viapizza"]` to work as I had hoped they would.

![image](https://user-images.githubusercontent.com/22780683/132022027-029078a0-cdec-4a11-ba84-95e739a4d20a.png)

Adblockers: uBO 1.37.3b20 + IDCAC 3.3.2
Browser: Chrome 93.0.4577.63 x64
OS: Windows 10 21H1 x64
Lists in use: ↓
![image](https://user-images.githubusercontent.com/22780683/132014947-4f8502a3-cfe7-42ce-9e16-e6259ba75ae3.png)

**Comment by Khrin** [comment]
I do agree that this site behaves weirdly. Also seems to have some hosting issue. The domain for the redirects was different to me, anyway both are now in EasyList.
