### ISSUE TITLE
Anti-Adblock

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylistdutch#30]
**Does EasyList Dutch allow anti-adblock rule?** 
*Since I have some rules for you, if the answer is yes.*

**Comment by BPower0036** [comment]
No, it does not.
See --> 
> @JohnyP36 Thanks for your contributions! As these are quite a lot of changes at once, please make sure your changes meet [ABP requirements](https://adblockplus.org/en/filter-lists-requirements). Most importantly anti-adblock shouldn't be tackled in this list (as it is illegal in some countries) and tracking filters should go into [EasyPrivacy](https://github.com/easylist/easylist) instead.
> _Originally posted by @monzta in https://github.com/easylist/easylistdutch/issues/11#issuecomment-818864565_

**Comment by JohnyP36** [comment]
> No, it does not. See -->
> 
> > @JohnyP36 Thanks for your contributions! As these are quite a lot of changes at once, please make sure your changes meet [ABP requirements](https://adblockplus.org/en/filter-lists-requirements). Most importantly anti-adblock shouldn't be tackled in this list (as it is illegal in some countries) and tracking filters should go into [EasyPrivacy](https://github.com/easylist/easylist) instead.
> > _Originally posted by @monzta in [#11 (comment)](https://github.com/easylist/easylistdutch/pull/11#issuecomment-818864565)_

Oké, but in the Netherlands it's not illegal.

**Comment by Khrin** [comment]
> **Does EasyList Dutch allow anti-adblock rule?**

No.

**Comment by BPower0036** [comment]
@Khrin 
However you can do what @gorhill said to me:

> Maintainer could add `!#include ...` directives to load the filters for uBO, ABP will ignore this.
> _Originally posted by @gorhill in https://github.com/uBlockOrigin/uAssets/issues/11204#issuecomment-1012114946_
