### ISSUE TITLE
nrc.nl

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistdutch#32]
Placeholders on the frontpage. I propose `nrc.nl##.banner--rectangle`
* Screenshot: ![image](https://user-images.githubusercontent.com/22780683/149193259-9c3f11cb-8436-4cf3-8e54-6dc1be4916c8.png)
* OS/version: Windows 11 x64
* Browser/version: Chrome 97.0.4692.71 x64
* Adblock Extension/version: uBO 1.40.5b1
* Subscriptions (Note that I also test with AdGuard Dutch Filter just in case): ![image](https://user-images.githubusercontent.com/22780683/149192842-60ed337d-d6cd-4c83-842b-0aa6a1f94ffe.png)

**Comment by JohnyP36** [comment]
Could also be `nrc.nl##.banner` 
as in [my list](https://github.com/JohnyP36/Personal-List/blob/99e767a38252a5e6a5c0b8753ddf6e28ee89a87f/easylistdutch/Hide%20(specific).txt#L37)

**Comment by Khrin** [comment]
@DandelionSprout 0 filters out of 1230?

**Comment by DandelionSprout** [comment]
@Khrin AdGuard Dutch Filter borrows all entries from EasyList Dutch, but I figured it'd look even more weird if I didn't have EasyList Dutch turned on at all.

**Comment by DandelionSprout** [comment]
That being said, I accept some blame for how it didn't strike me to experiment with enabling lists in a different order, in order to make dual-list entries be credited to EasyList Dutch instead. This is how the sections should've shown up as: 
![image](https://user-images.githubusercontent.com/22780683/149395962-34b22753-92a2-4042-a005-a505c13578f0.png)

**Comment by DandelionSprout** [comment]
My case probably isn't helped by how `nrc.nl,(...)##.banner` only now (today) seemed to be registered properly by my uBO installation.
