### ISSUE TITLE
nd.nl

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistdutch#33]
A small placeholder (but with text) on the frontpage. I propose `nd.nl##.desktoponly > .text-center`
* Screenshot: 
![image](https://user-images.githubusercontent.com/22780683/149196380-14df0043-df5e-4071-9ab2-f4cd5587e790.png)
* OS/version: Windows 11 x64
* Browser/version: Chrome 97.0.4692.71 x64
* Adblock Extension/version: uBO 1.40.5b1
* Subscriptions (Note that I also test with AdGuard Dutch Filter just in case): ![image](https://user-images.githubusercontent.com/22780683/149192842-60ed337d-d6cd-4c83-842b-0aa6a1f94ffe.png)

**Comment by JohnyP36** [comment]
Maybe better is `nd.nl#?#.text-center:-abp-contains(advert)` 
in case there are more boxes with `##.desktoponly > .text-center` which don't contain ads.

**Comment by Khrin** [comment]
Honestly I don't think it's really worthwhile to be added.
