### ISSUE TITLE
nnp.nl

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistdutch#35]
Placeholder on the right on the frontpage. I propose `nnp.nl##.p-4.bg-gray-100`
* Screenshot: ![image](https://user-images.githubusercontent.com/22780683/149198608-d1f3ff9e-be4d-4940-b5ca-8ced6bfc698e.png)
* OS/version: Windows 11 x64
* Browser/version: Chrome 97.0.4692.71 x64
* Adblock Extension/version: uBO 1.40.5b1
* Subscriptions (Note that I also test with AdGuard Dutch Filter just in case): ![image](https://user-images.githubusercontent.com/22780683/149192842-60ed337d-d6cd-4c83-842b-0aa6a1f94ffe.png)

**Comment by JohnyP36** [comment]
`nnp.nl##.p-4.bg-gray-100` only blocks half of the grey. 
So I propose `nnp.nl#?#div[class^="p-4 bg-gray-100"]:-abp-has(div[class^="p-4"])`

**Comment by Khrin** [comment]
@DandelionSprout Is it really necessary to block it?

**Comment by DandelionSprout** [comment]
Good question. I presumed a 400x350px placeholder would be supposed to be blocked, even when it doesn't really affect anything nor freeing up any space.

**Comment by Khrin** [comment]
> Good question. I presumed a colored 400x350px placeholder would be supposed to be blocked, even when it doesn't really affect anything nor freeing up any space.

I don't think so, in this case.
