### ISSUE TITLE
beursgorilla.nl

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistdutch#37]
What seems to be a placeholder on the right. I propose `beursgorilla.nl##.ut--rectangle`
* Screenshot: ![image](https://user-images.githubusercontent.com/22780683/149200007-f0972e1c-b06c-4232-a9b4-9bf4958d9234.png)
* OS/version: Windows 11 x64
* Browser/version: Chrome 97.0.4692.71 x64
* Adblock Extension/version: uBO 1.40.5b1
* Subscriptions (Note that I also test with AdGuard Dutch Filter just in case): ![image](https://user-images.githubusercontent.com/22780683/149192842-60ed337d-d6cd-4c83-842b-0aa6a1f94ffe.png)

**Comment by JohnyP36** [comment]
The rules of: https://github.com/easylist/easylistdutch/blob/13f3aa3e9935dce291102299a72c480ccf0c810f/easylistdutch/hide_specific.txt#L317
and https://github.com/easylist/easylistdutch/blob/13f3aa3e9935dce291102299a72c480ccf0c810f/easylistdutch/hide_specific.txt#L318 

are outdated and need to replaced with
```
beursgorilla.nl##.js--billboard.ut--billboard
beursgorilla.nl##.js--rect.ut--rectangle
```

###### *See [here](https://github.com/JohnyP36/Personal-List/blob/99e767a38252a5e6a5c0b8753ddf6e28ee89a87f/easylistdutch/Hide%20(specific).txt#L116)*

**Comment by Khrin** [comment]
@DandelionSprout update the list, do you still see the empty placeholders?
