### ISSUE TITLE
Links to our sponsors blocked on www.meerdangewenst.nl

### ISSUE THREAD

**Issue by stkams** [easylist/easylistdutch#47]
in easylistdutch there are two entries that block links to sponsors of our non-profit organisation. These links are _not_ ads.

block_first_party_resource.txt: `||meerdangewenst.nl^*/sponsors/`
hide_specific.txt: `meerdangewenst.nl##.tg-site-footer-section-1`

Could these entries be removed, please?

### List the website(s) you're having issues:

https://www.meerdangewenst.nl

### What happens?

Links to sponsors of our non-profit organisation are removed. These links are _not_ ads.

### List Subscriptions you're using:

Noticed with AdGuard

### Other details:

You can contact the webmaster (me) on the usual email address if confirmation is required.

I can create a pull request myself if desired.

**Comment by JohnyP36** [comment]
@stkams That's true. But in easylistdutch they also block images of sponsors, because they see them as indirect advertisement.

**Comment by stkams** [comment]
Sponsors help keeping our organisation going. That they want some presence in return is understandable, and they are closely related.

You could indeed argue that it's the same as some free site using paid ads but the website of an NGO/non-profit organisation is something different than a commercial site.

**Comment by Khrin** [comment]
@stkams Interesting feedback, but the filters won't be removed.
