### ISSUE TITLE
DPG media: use volkskrant.nl rules for other domains

### ISSUE THREAD

**Issue by twiddle-hobbies** [easylist/easylistdutch#65]
Recently in e8a3c1a3830388d4249413ce5411e1103d15992c, there were three rules added for `volkskrant.nl`.

```
volkskrant.nl###article_paragraph_3
volkskrant.nl##.mid1-container
volkskrant.nl##.top1-container
```
Other sites from DPG media `trouw.nl`, `parool.nl`,  and `demorgen.be` use the same/a very similar backend. 

Examples pages:

- `https://www.volkskrant.nl/economie/cbs-particuliere-verhuur-nam-meer-toe-dan-sociale-huur-en-koophuizen~bc689018/`
- `https://www.trouw.nl/duurzaamheid-economie/philips-schikt-voor-1-1-miljard-aan-claims-in-slaapapneu-affaire~b2e965be/`
- `https://www.parool.nl/sport/paauw-nijland-en-van-der-laan-strijden-om-voorzitterschap-knvb~be82a1b9/`
- `https://www.demorgen.be/snelnieuws/spaanse-premier-pedro-sanchez-blijft-toch-aan-na-rechtse-aanvallen-tegen-zijn-echtgenote-democratie-verdedigen~ba660109/`

Furthermore I suggest to add
```
#article_paragraph_1
#article_paragraph_6
```
for an advertisement containers only visible in the mobile version of this site. They can be found in the `parool.nl` article. I did not immediately find a good example of `#article_paragraph_6` articles for the other sites, but given the similarities they will probably appear somewhere. 

In a longer article behind a paywall (`https://www.volkskrant.nl/buitenland/regeren-met-radicaal-rechts-is-in-finland-al-praktijk-hoe-ziet-dat-eruit~b2d9e6a6/`) there was even a `#article_paragraph_9`, but without any content.

**Comment by Khrin** [comment]
@twiddle-hobbies Better to keep the filter as specific as possible.

**Comment by twiddle-hobbies** [comment]
@Khrin Thanks! The `#article_paragraph_1` is definitely used in all 4 sites though (only visible in a mobile browser).
